# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: prettier --write -l
        language: node
        types_or: ["text"]
        exclude_types: ["editorconfig", "gitignore"]
        additional_dependencies:
          - "prettier@^3.3.3"
          - "prettier-plugin-astro@^0.14.1"
        always_run: true
      - id: astro-check
        name: astro check
        entry: astro check
        language: node
        files: "^(?:public|src)/.+|astro\\.config\\.mjs|tsconfig\\.json"
        pass_filenames: false
        additional_dependencies:
          - "astro@^4.16.13"
          - "@astrojs/check@^0.9.4"
      - id: astro-build
        name: astro build
        entry: astro build
        language: node
        files: "^(?:public|src)/.+|astro\\.config\\.mjs|tsconfig\\.json"
        pass_filenames: false
        additional_dependencies:
          - "astro@^4.16.13"
